name: 'Dependency Review'

on:
  pull_request:
    branches: [ "master", next ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-Review:
    name: Review
    uses: bagtoad-enterprise-cloud-testing/public-actions/.github/workflows/dependency-review.yml@main
    with:
      public: true
      distributed: true
 
 
